---
title: "Gapminder"
output: html_document
date: "2026-03-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Libraries
```{r}
library(tidyverse)
library(tibble)
library(janitor)
library(naniar)
library(dplyr)
library(shiny)
library(shinydashboard)
library(shinythemes)
```

#Data set and cleaning

```{r}
gapminder_life_expectancy<- read.csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/Data/Life_expectancy.csv") 
```

```{r}
co2_emissions<-read_csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/Data/co2_pcap_cons.csv")
```

```{r}
Pop<-read_csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/Data/pop.csv")
```

```{r}
Hiv_death<-read_csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/Data/hiv_death.csv")
```
```{r}
Child_death<- read.csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/Data/number_of_child_deaths.csv")

```

```{r}
kcals_per_day<- read_csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/Data/kilocalories_per_person_and_day.csv")
```

```{r}
gdp<- read_csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/Data/gdp.csv")
```
```{r}
lung_cancerF<- read_csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/Data/lung_cancer_f.csv")
```

```{r}
lung_cancerM<- read_csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/Data/lung_cancer_m.csv")
```


#pivoting and fixing year + other problems

```{r}
gapminder_life_expectancy<- gapminder_life_expectancy %>% 
  pivot_longer(-c(name,geo),
               names_to = "year",
               values_to = "life_expectancy") %>% 
  mutate(year= str_remove(year, "X"))
```

```{r}
Child_death<-Child_death %>% 
pivot_longer(-c(name,geo),
               names_to = "year",
               values_to = "cild_death") %>% 
  mutate(year= str_remove(year, "X")) 
```

```{r}
co2_emissions<- co2_emissions %>% 
  pivot_longer(-c(geo,name),
               names_to = "year",
              values_to = "Co2_emissions")
```

```{r}
pop<- Pop %>% 
  pivot_longer(-c(geo,name),
               names_to = "year",
              values_to = "population")
```

```{r}
hiv_death<- Hiv_death %>% 
  pivot_longer(-c(geo,name),
               names_to = "year",
               values_to = "hiv_deaths")
```

```{r}
kcals_per_day<- kcals_per_day %>% 
  pivot_longer(-c(geo,name),
               names_to = "year",
               values_to = "kcal")
```

```{r}
gdp<- gdp %>% 
  pivot_longer(-c(geo,name),
               names_to = "year",
               values_to = "gdp")
```

```{r}
 lung_cancerF<-lung_cancerF %>% 
  pivot_longer(-c(geo,name),
               names_to = "year",
               values_to = "lung_cancerf")
```
  
```{r}
 lung_cancerM<-lung_cancerM %>% 
  pivot_longer(-c(geo,name),
               names_to = "year",
               values_to = "lung_cancerm")
```

#joining data tables

```{r}
gp<-full_join(Child_death, gapminder_life_expectancy, by= c("name", "geo","year"))
```

```{r}
gp2<-full_join(gp, co2_emissions, by= c("name", "geo","year"))
```

```{r}
gp3<-full_join(gp2,pop, by= c("name", "geo","year"))
```

```{r}
gp4<-full_join(gp3,hiv_death, by= c("name", "geo", "year") )
```

```{r}
gp5<- full_join(gp4, kcals_per_day, by = c("name","geo","year"))
```

```{r}
gp6<- full_join(gp5, gdp, by = c("name", "year","geo") )
```

```{r}
gp7<- full_join(gp6,lung_cancerF, by = c("name", "year","geo") )
```

```{r}
gapminder<- full_join(gp7,lung_cancerM, by = c("name", "year","geo") )
```


```{r}
gapminder<- gapminder %>% 
  filter(year>= "1915", year<="2025")
```


#final data set

```{r}
gapminder
```

```{r}
write.csv(gapminder, file="gapminder.csv", row.names=FALSE)
```

```{r}
gapminder<-read_csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/Gapminder/gapminder.csv")
gapminder
```

#understanding the data
```{r}
gg_miss_var(gapminder)
```

```{r}
gapminder %>% 
  miss_var_summary(order=T)
```

average co2_emissions from 2019-2025?
```{r}
gapminder %>% 
  select(names, Co2_emissions, year) %>% 
  pivot_wider(names_from = "year",
              values_from= "Co2_emissions" ) %>% 
  
```

```{r}
gapminder %>% 
  select(name, Co2_emissions, year) %>% 
  pivot_wider(names_from = "name",
              values_from = "Co2_emissions")
```


#graphs

```{r}

```






Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
