---
title: "Shiny_app3"
date: "2026-03-11"
output: html_document
---
#load libraries 
```{r}
library(leaflet)
library(tidyverse)
library(shiny)
library(shinydashboard)
library(shinythemes)
```

#load data
```{r}
gapminder<- read_csv("gapminder.csv")
```
#shiny app fully done by joanna as well
```{r}
library(shiny)
#what the user sees
ui <- fluidPage(
  #button to show info popup
  actionButton("show", "Info"),
  #theme styling
  theme = shinytheme("superhero"),
  #app title
   titlePanel("CO2 Emission For Each Continent Throughout the Years"),
  
  sidebarLayout(
    #sidebar controls
    sidebarPanel(
      #sidebar to choose year (with animation)
      sliderInput("year",
                  label = "choose year",
                  min = 1980,
                  max = 2022,
                  value = 2000,
                  step = 1,
                  sep = "",
                  #animation feature
                  animate = animationOptions(
                    interval = 200,
                    loop = T,
                    playButton = "play",
                    pauseButton = "pause"
                  ))
    ),
    #map output
    mainPanel (
      leafletOutput("map", height = "500px")
    )
  )
)

server <- function(input, output, session) {
 #render the leaflet map 
  output$map <- renderLeaflet({
    #filter data for selected year
    map_data <- gapminder %>% 
      filter(year == input$year) 
    
    #create map
    leaflet(map_data) %>% 
      #darktheme map tiles
      addProviderTiles("Stadia.AlidadeSmoothDark") %>%
      #circle markers for each data point
      addCircleMarkers(
        #coordinates
        lng = ~as.numeric(longitude),
        lat = ~as.numeric(latitude),
        #size based on co2 emission
        radius = ~2*(Co2_emissions),
        #styling 
        color = "brown",
        fillColor = "tomato", 
        weight = 3
      ) 
  })
  #info tab
  observeEvent(input$show, {
    showModal(modalDialog(
      title = "About Graph and App",
      "In this app, users can select a year using the slider to see the CO2 emissions from all continents from that year. An animation is included to see the CO2 emissions from all continents from the years 1980 to 2022 by pressing the 'play' button",
      footer = modalButton("OK!")
    ))
  })
}

shinyApp(ui, server)
```

```{r}
gapminder %>% 
  select(Co2_emissions)
```


