---
title: "Shiny app"
output: html_document
date: "2026-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("bsicons")
install.packages("shinyBS")
```


```{r}
#load required packages 
library(tidyverse)
library(shiny)
#shiny+UI tools 
library(shinydashboard)
library(shinythemes)
library(bslib)
library(bsicons)
library(shinyBS)
```

#load data (mia)
```{r}
gapminder<-read_csv("gapminder.csv")
#gapminder
```


#shiny app
```{r}
ui <- fluidPage(
  #button to show app info (Joanna)
  actionButton("show", "Info"),
  #theme (joanna)
  theme = shinytheme("superhero"),
  #app title (joanna)
  titlePanel("Countries Throughout the Years"),
  
  sidebarLayout(
    sidebarPanel(
      
      #country selector (joanna)
      selectInput("filter",
              "select country",
              choices = unique(gapminder$name),
              selected = "Afghanistan"),
      #variable selector (mia)
      selectInput("y",
              "Select Variable",
              choices = c("life_expectancy",
                          "Co2_emissions",
                          "population",
                          "gdp"),
              selected = "population"), 
     #year range slider (joanna) 
      sliderInput("Range",
              label = "choose years",
              min = min(gapminder$year, na.rm = T),
              max = max(gapminder$year, na.rm = T),
              value = c(1915, 2022),
              step = 1,
              sep = "")
    ),
    
    mainPanel(
      
      fluidRow(
       #plot 1 (mia) column(6,
               h4(textOutput("plot1_title")),
               plotOutput("plot1", height = "500px")
               ),
        
     #plot 2 (mia)   column(6,
               h4("USA Throughout the Years"),
               plotOutput("plot2", height = "500px"))
        )
      )
    
  

server <- function(input, output, session) {
  
#title for the plot (mia)
  output$plot1_title <- renderText(paste(input$filter, "throughout years"))
  
  output$plot1 <- renderPlot({
    
    gapminder %>% 
      filter(name == input$filter,
             year >= input$Range[1],
             year <= input$Range[2]) %>% 
      ggplot(aes(x=year, y=.data[[input$y]], na.rm=T))+
      scale_y_log10()+
      geom_line(color= "yellow")+
      geom_point(na.rm=T, shape=1, color= "blue")+
      scale_x_continuous(limits = input$Range)+
      theme(legend.position = "none",
            axis.text.x = element_text(hjust=1, size = 25),
            axis.text.y = element_text(hjust = 1, size = 20))+
      labs(x="Year")
    })
  
 #plot 2, usa comparison (mia) 
  output$plot2<-renderPlot({
    gapminder %>% 
      filter(name=="USA",
             year >= input$Range[1],
             year <= input$Range[2]) %>% 
      ggplot(aes(x=year, y=.data[[input$y]]))+
      geom_line(aes(color="tomato"))+
      geom_point(shape=1, na.rm=T, color="blue")+
      scale_y_log10()+
      scale_x_continuous(limits = input$Range)+
      theme(axis.text.x = element_text( hjust=1, size=25),
            axis.text.y = element_text (hjust=1, size=20), 
            legend.position= "none")+
      labs(title="USA throughout years",
           x="Years",
           y=input$y)
    })
  #info tab (joanna)
  observeEvent(input$show, {
    showModal(modalDialog(
      title = "About Graph and App",
      "In this app, users can select from any country and see that county's trends for life expectancy, population, CO2 emissions, and GDP per capita compared to the trends in the USA. Users can also use the slider to set a range of years for the x axis of the graph",
      footer = modalButton("OK!")
    ))
  })
  
}

shinyApp(ui, server)
```


