---
title: "shiny app 2"
output: html_document
date: "2026-03-10"
---

```{r}
install.packages("plotly")
library(plotly)
library(tidyverse)
library(tibble)
library(janitor)
library(naniar)
library(dplyr)
library(shiny)
library(shinydashboard)
library(shinythemes)
```

```{r}
gapminder<- read_csv("gapminder.csv")
```

#shiny app (fully done by joanna)

```{r}
library(shiny)
#what the user sees
ui <- fluidPage( 
  #info button popup
  actionButton("show", "Info"),
  #theme
  theme = shinytheme("superhero"),
  
  sidebarLayout(
    
    sidebarPanel(
   #select continents   
      checkboxGroupInput("continents",
                         label = "select",
                         choices = unique(gapminder$continent),
                         selected = unique(gapminder$continent)
                         ),
    #year slider with animation  
      sliderInput("year",
              label = "choose years",
              min =1980,
              max =  2022,
              value = 2000,
              step = 1,
              sep = "",
              animate = animationOptions(
                interval = 250, 
                loop = T,
                playButton = "play",
                pauseButton = "pause"
              ))
    ),
    
    mainPanel(
      
      fluidRow(
        column(12,
               h4(textOutput("plot_title")),
               plotlyOutput("plot", height = "500px")
    )
   )
  )
 )
)

 

server <- function(input, output, session) {
#title   
  output$plot_title <- renderText(paste("Life Expectancy versus GDP per Capita"))
  #interactive plot 
  output$plot <- renderPlotly({
    
    p <- gapminder %>%
      filter(year == input$year,
             continent %in% input$continents) %>% 
      ggplot(aes(x=gdp, y=life_expectancy, colour = continent, text= paste0("Country: ", name, 
                                                                            "\nGDP per capita: ", gdp, 
                                                                            "\nLife Expectancy: ", life_expectancy)))+
      geom_point(alpha = 0.7)+
      scale_x_log10()+
      scale_x_continuous(limits = input$Range)+
      theme(axis.text.x = element_text(hjust=1, size = 20),
            axis.text.y = element_text(hjust = 1, size = 20))+
      labs(x= "GDP per Capita", 
           y= "Life Expectancy",
           color = "Continents")
    
      ggplotly(p, tooltip = "text")
    })
  #info popup 
  observeEvent(input$show, {
    showModal(modalDialog(
      title = "About Graph and App",
      "In this app, users can select and deselect continents to see a scatterplot of that continent's life expectancy versus GPD per capita. Continents are color coded. Each point on the scatterplot represents one country of the respected continent. Users can hover over a point to get more information of that represented country including the country name, its GDP per capita, and life expectancy. There is also a function that allows the user to compare the numbers of other points close by. Users can also use the slider to find a certain year to further investigate. An animation of the trend is also included if the user presses the 'play' button",
      footer = modalButton("OK!")
    ))
  })
  
}

shinyApp(ui, server)
```