---
title: "Ducks_egg_data"
output: html_document
date: "2026-02-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(tibble)
library(janitor)
library(naniar)
library(dplyr)
```

```{r}
ducks<- read.csv("C:/Users/Miala/OneDrive/Desktop/BIS15L_W2026_Group9/data/doi_10_5061_dryad_0k6djhb8q__v20240808/cleanData6.6.24.csv", na="unknown") %>% 
  clean_names()
ducks
```

```{r}
summary(ducks)
```


#graphs of eggs in which type of nest, which species more in thier own nest vs mixed nest

```{r}
ducks %>%
  mutate(host= ifelse(host == 1, "Wood Duck", "Hooded Merganser")) %>% 
  select(host,nest) %>% 
  group_by(nest, host) %>% 
  summarise(count_nest= n()) %>% 
  ggplot(aes(x=nest, y=count_nest, fill = host))+
  geom_col(position = "dodge")+
  labs(title = "Number of Eggs of Each Species in Nesting Types", fill = "Duck Species", x= "Nesting Types",
       y="Count")
```

#Graph of egg survival of 2 species

```{r}
ducks %>% 
  mutate(host= ifelse(host == 1, "Wood Duck", "Hooded Merganser")) %>%
  select(host, nestfate) %>% 
  group_by(nestfate, host) %>% 
  summarise(count_fate= n()) %>% 
  ggplot(aes(x=host, y=count_fate, fill = nestfate))+
  geom_col(position = "dodge")+
  labs(title = "Number of Failed vs Hatched Eggs in Each Species", fill = "Fate", x= "Species", y="Number of Eggs")
```


#graph of egg survival btw 2 states (shinyapp, select which state) 

```{r}

```

#avg hatch size of each species
```{r}
ducks %>% 
  mutate(host= ifelse(host == 1, "Wood Duck", "Hooded Merganser")) %>%
  select(hatch, host, id) %>% 
  mutate(hatch= as.numeric(hatch)) %>% 
   group_by(host) %>%
  summarise(avg_hatchsize=mean(hatch))
  
  
  

   
```

#avg hatch size of each species vs survivability of each species (shiny app)

```{r}
library(shiny)

ui <- fluidPage(
  selectInput("x",
              choices = c("nestfate")),
  selectInput("y",
              choices = c(""))
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```
#clutch and hatch


```{r}
ducks %>% 
   mutate(host= ifelse(host == 1, "Wood Duck", "Hooded Merganser")) %>%
  select(host, id, clutch, hatch) %>% 
  filter(host== "Wood Duck") %>% 
   mutate(hatch= as.numeric(hatch),
          clutch= as.numeric(clutch)) %>%
group_by(id) %>% 
  summarize(clutch_hatched= clutch-hatch) %>% 
  ggplot(aes(x= id, y=clutch_hatched))+
  geom_point()
```
```{r}
```


```{r}
?.group
```

